export const FETCH_OFFER_SLIDER_REQUEST = "FETCH_OFFER_SLIDER_REQUEST";
export const FETCH_OFFER_SLIDER_SUCCESS = "FETCH_OFFER_SLIDER_SUCCESS";
export const FETCH_OFFER_SLIDER_FAILURE = "FETCH_OFFER_SLIDER_FAILURE";
export const RESET_OFFER = "RESET_OFFER";
export const FETCH_OFFERS_REQUEST = "FETCH_OFFERS_REQUEST";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_FAILURE = "FETCH_OFFERS_FAILURE";

export const FETCH_OFFER_REFRESH = "  FETCH_OFFER_REFRESH";

export const FETCH_OFFER_ERROR = "FETCH_OFFER_ERROR";
