// actionTypes.js
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_RESET = "FETCH_USER_RESET";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const FETCH_USER_OTP_DETAILS_REQUEST = "FETCH_USER_OTP_DETAILS_REQUEST";
export const FETCH_USER_OTP_DETAILS_SUCCESS = "FETCH_USER_OTP_DETAILS_SUCCESS";
export const FETCH_USER_OTP_DETAILS_FAILURE = "FETCH_USER_OTP_DETAILS_FAILURE";
export const FETCH_USER_OTP_DETAILS_RESET = "FETCH_USER_OTP_DETAILS_RESET";







export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const ADD_USER_RESET = "ADD_USER_RESET";

export const USER_PASSWORD_RESET_REQUEST = "USER_PASSWORD_RESET_REQUEST";
export const USER_PASSWORD_RESET_SUCCESS = "USER_PASSWORD_RESET_SUCCESS";
export const USER_PASSWORD_RESET_FAILURE = "USER_PASSWORD_RESET_FAILURE";
export const USER_PASSWORD_RESET_RESET = "USER_PASSWORD_RESET_RESET";

export const FETCH_USER_DETAILS_REQUEST = "FETCH_USER_DETAILS_REQUEST";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";
export const UPDATE_USER_DETAILS_RESET = "UPDATE_USER_DETAILS_RESET";

export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
