// actionTypes.js
export const FETCH_WEB_REQUEST = "FETCH_WEB_REQUEST";
export const FETCH_WEB_SUCCESS = "FETCH_WEB_SUCCESS";
export const FETCH_WEB_FAILURE = "FETCH_WEB_FAILURE";
export const   FETCH_WEB_REFRESH = "  FETCH_WEB_REFRESH";
export const RESET_WEB = "RESET_WEB";

export const FETCH_WEB_DETAILS_REQUEST = "FETCH_WEB_DETAILS_REQUEST";
export const FETCH_WEB_DETAILS_SUCCESS = "FETCH_WEB_DETAILS_SUCCESS";
export const FETCH_WEB_DETAILS_FAILURE = "FETCH_WEB_DETAILS_FAILURE";

export const UPDATE_WEB_DETAILS_REQUEST = "UPDATE_WEB_DETAILS_REQUEST";
export const UPDATE_WEB_DETAILS_SUCCESS = "UPDATE_WEB_DETAILS_SUCCESS";
export const UPDATE_WEB_DETAILS_FAILURE = "UPDATE_WEB_DETAILS_FAILURE";
export const UPDATE_WEB_DETAILS_RESET = "UPDATE_WEB_DETAILS_RESET";

export const ADD_WEB_DETAILS_REQUEST = "ADD_WEB_DETAILS_REQUEST";
export const ADD_WEB_DETAILS_SUCCESS = "ADD_WEB_DETAILS_SUCCESS";
export const ADD_WEB_DETAILS_FAILURE = "ADD_WEB_DETAILS_FAILURE";
export const ADD_WEB_DETAILS_RESET = "ADD_WEB_DETAILS_RESET";

export const FETCH_WEB_ERROR = "FETCH_WEB_ERROR";
